---
- name: Primer play de el curso
  hosts: servidores_de_aplicaciones

  tasks:
  - name: Hacer un ping
    ansible.builtin.ping:
  - name: Crear un fichero
    ansible.builtin.shell:
      touch /tmp/fichero1.txt
  - name: Copiar un fichero
    ansible.builtin.copy:
       "src=/tmp/fichero1.txt dest=/tmp/fichero1.txt"